version: 2.1

orbs:
  vault: contentful/vault@1
  node: circleci/node@5.1.0

jobs:
  lint:
    docker:
      - image: 'cimg/node:18.17.1-browsers'
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'packages-read'
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_WRITE_TOKEN}" > ~/.npmrc
      - run: echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - node/install-packages
      - run: npm run lint
      - run: npm run prettier:check
      - run: npm run build
      - run: npm run test:size
      - run: npm run test:types

  unit:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '18.17'
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'packages-read'
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_WRITE_TOKEN}" > ~/.npmrc
      - run: echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - node/install-packages
      - run: npm run test:unit

  integration:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '18.17'
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'packages-read'
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_WRITE_TOKEN}" > ~/.npmrc
      - run: echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - node/install-packages
      - run: npm run test:integration

  release:
    docker:
      - image: 'cimg/node:18.17.1-browsers'
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'semantic-release-ecosystem'
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_WRITE_TOKEN}" > ~/.npmrc
      - run: echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - node/install-packages
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          context: vault
      - unit:
          context: vault
      - integration:
          context: vault
      - release:
          context: vault
          requires:
            - unit
            - integration
